[package]
name = "oracle"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]

# reth
reth-node-ethereum.workspace = true
reth.workspace = true
reth-tracing.workspace = true
reth-network-peers.workspace = true
reth-discv5.workspace = true
reth-exex.workspace = true
reth-node-api.workspace = true

# networking
discv5 = "0.6"
enr = "0.12"

# async
futures.workspace = true
tokio.workspace = true

# misc
clap = "4" 
eyre.workspace = true
